// Getters
export const GET_SIM_MAP = 'simulations/GET_SIM_MAP'
export const GET_SIM_ARR = 'simulations/GET_SIM_ARR'
export const GET_SIM_UPDATED = 'simulations/GET_SIM_UPDATED'
export const GET_CHART_UPDATED = 'views/GET_CHART_UPDATED'
export const GET_GRAPH_STATE_MAP = 'mainView/GET_GRAPH_STATE_MAP'
export const GET_CHART_ARR = 'mainView/GET_CHART_ARR'
export const DEFAULT_TWOD_PRTL_HIST = 'defaultGraphs/TWO_D_PRTL_HIST'
export const AVAIL_CHART_TYPES = 'defaultGraphs/AVAIL_CHART_TYPES'
export const GET_SERVER_MAP = 'servers/GET_SERVER_MAP'
export const GET_SERVER_ARR = 'servers/GET_SERVER_ARR'
export const GET_NEXT_CHART_ID = 'views/GET_NEXT_CHART_ID'

// Mutations
export const PUSH_SIMULATION = 'simulations/PUSH_SIMULATION'
export const POP_SIMULATION = 'simulations/POP_SIMULATION'
export const PUSH_GRAPH = 'mainView/PUSH_GRAPH'
export const POP_GRAPH = 'mainView/POP_GRAPH'
export const TOGGLE_SIDEBAR = 'sidebar/TOGGLE_SIDEBAR'
export const PUSH_SERVER = 'servers/PUSH_SERVER'
export const POP_SERVER = 'servers/POP_SERVER'
export const MUTATE_TSTEP = 'sims/MUTATE_TSTEP'
export const MARK_UPDATE = 'views/MARK_UPDATE'
export const MUTATE_CHART_OPT = 'views/MUTATE_CHART_OPT'

// Actions
export const OPEN_SIMULATION = 'simulations/OPEN_SIMULATION'
export const DEL_SIMULATION = 'simulations/DEL_SIMULATION'
export const OPEN_GRAPH = 'mainView/OPEN_GRAPH'
export const ADD_GRAPH = 'mainView/ADD_GRAPH'
export const DEL_GRAPH = 'mainView/DEL_GRAPH'
export const ADD_SERVER = 'servers/ADD_SERVER'
export const DEL_SERVER = 'servers/DEL_SERVER'
export const CHANGE_SIM_TSTEP = 'sims/CHANGE_SIM_TSTEP'
export const UPDATE_CHART = 'views/UPDATE_CHART'
export const TOGGLE_UPDATE = 'views/TOGGLE_UPDATE'
